// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ82yXNlEnYXaTgAkpwsLom7KVJAYojbI',
    appId: '1:756378779922:web:ea91dac64356b108a4f3cb',
    messagingSenderId: '756378779922',
    projectId: 'vibezcheck-548bc',
    authDomain: 'vibezcheck-548bc.firebaseapp.com',
    storageBucket: 'vibezcheck-548bc.firebasestorage.app',
    measurementId: 'G-B1LLLB7ZW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI396t5YCgp03zP3kNxidBWGhtaDfVswo',
    appId: '1:756378779922:android:0cc6713b14a747bfa4f3cb',
    messagingSenderId: '756378779922',
    projectId: 'vibezcheck-548bc',
    storageBucket: 'vibezcheck-548bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_E_ZJucXNK_PcqGiQ8EmEyK6E_rhmfk',
    appId: '1:756378779922:ios:e4d10e6b424e2694a4f3cb',
    messagingSenderId: '756378779922',
    projectId: 'vibezcheck-548bc',
    storageBucket: 'vibezcheck-548bc.firebasestorage.app',
    iosBundleId: 'com.example.vibezcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD_E_ZJucXNK_PcqGiQ8EmEyK6E_rhmfk',
    appId: '1:756378779922:ios:e4d10e6b424e2694a4f3cb',
    messagingSenderId: '756378779922',
    projectId: 'vibezcheck-548bc',
    storageBucket: 'vibezcheck-548bc.firebasestorage.app',
    iosBundleId: 'com.example.vibezcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ82yXNlEnYXaTgAkpwsLom7KVJAYojbI',
    appId: '1:756378779922:web:4bb3fc87e4628c9aa4f3cb',
    messagingSenderId: '756378779922',
    projectId: 'vibezcheck-548bc',
    authDomain: 'vibezcheck-548bc.firebaseapp.com',
    storageBucket: 'vibezcheck-548bc.firebasestorage.app',
    measurementId: 'G-DFR500KC4B',
  );
}
